const templateManager = {
  _templates: [],
  _builtinTemplates: [],
  _activeTemplate: null,
  _db: null,

  async _openDB() {
    if (this._db) return this._db;
    return new Promise((resolve, reject) => {
      const req = indexedDB.open('editgc-templates', 2);
      req.onupgradeneeded = e => {
        const db = e.target.result;
        if (!db.objectStoreNames.contains('handles')) db.createObjectStore('handles');
        if (!db.objectStoreNames.contains('templates')) db.createObjectStore('templates');
      };
      req.onsuccess = e => { this._db = e.target.result; resolve(this._db); };
      req.onerror = () => reject(req.error);
    });
  },

  loadBuiltin() {
    this._builtinTemplates = [
      {
        name: "GRBL 1.1h", author: "gnea", programName: "GRBL Laser",
        ext: "gcode", lineEnd: "\r\n",
        customCommands: [], toolCodes: [],
        laserOnCmd: "M4 S0", laserOffCmd: "M5 S0",
        header: ["; Generated by Edit.GC", "; Machine: GRBL 1.1h", "G21", "G90", "G92 X0 Y0 Z0"],
        footer: ["M5 S0", "G0 X0 Y0", "M2"],
        feedCut: 3000, feedTravel: 6000, sMax: 1000
      },
      {
        name: "Smoothieware", author: "Smoothieboard", programName: "Smoothie Laser",
        ext: "gcode", lineEnd: "\n",
        customCommands: [], toolCodes: [],
        laserOnCmd: "M3 S0", laserOffCmd: "M5",
        header: ["; Generated by Edit.GC", "; Machine: Smoothieware", "G21", "G90"],
        footer: ["M5", "G0 X0 Y0", "M2"],
        feedCut: 3000, feedTravel: 6000, sMax: 1000
      },
      {
        name: "Marlin (Laser)", author: "Marlin Firmware", programName: "Marlin Laser",
        ext: "gcode", lineEnd: "\n",
        customCommands: [], toolCodes: [],
        laserOnCmd: "M3 S0", laserOffCmd: "M5",
        header: ["; Generated by Edit.GC", "; Machine: Marlin (Laser Mode)", "G21", "G90", "G92 X0 Y0 Z0"],
        footer: ["M5", "G0 X0 Y0", "M84"],
        feedCut: 3000, feedTravel: 6000, sMax: 1000
      },
       {
         name: "SM Motion Control (SM300)", programName: "SM300",
        ext: "cnc", lineEnd: "\r\n",
        customCommands: ["G22$L_READY$01", "G22$L_TEST$01", "G48%=0005", "G98$SPROG$", "G99", "RA3", "RA4", "RLAD", "RM12", "RM3", "RRBM", "SA3", "SM12", "SM3", "G26H", "M14", "G04T", "G04TR", "G60", "G62", "RAIN", "ROUT", "RTST", "RAOT", "RMUL", "RSUB", "RADD"],
        commandComments: {
          "SM3": "Laser start", "RM3": "Laser Stop",
          "SM12": "Protective Gas ON", "RM12": "Protective Gas OFF",
          "SA3": "Close safety circuit DBM circuit board", "RA3": "Open safety DBM circuit board",
          "RA4": "Open safety DBM (variant)",
          "RLAD": "Select laser program / Load axis data to register",
          "RRBM": "Set Laser program / Store register value",
          "G98$SPROG$": "Start Program subprogram", "G99": "End of Program subprogram",
          "G22$L_READY$01": "Laser Ready", "G22$L_TEST$01": "Test Laser locked",
          "G48%=0005": "Parameter setting",
          "G26H": "Handbetrieb (manual mode / wait for user input)",
          "M14": "Take over actual value as setpoint",
          "G04T": "Wait / dwell time (seconds)",
          "G04TR": "Wait / dwell time (rapid)",
          "G60": "Arc mode OFF (linear interpolation)",
          "G62": "Arc mode ON (circular interpolation)",
          "RAIN": "Read analog input to register",
          "ROUT": "Set digital output",
          "RTST": "Read/test input condition",
          "RAOT": "Set analog output",
          "RMUL": "Register multiply",
          "RSUB": "Register subtract",
          "RADD": "Register add"
        },
        toolCodes: [],
        laserOnCmd: "SM3", laserOffCmd: "RM3",
        header: [";********************************************************", ";   Programmname   :  SM300", ";   Version        :  1.0", ";********************************************************", "", "G98$SPROG$", "SA3", "RLAD R10;55", "RRBM R10;50;56", "SM12", "SM3"],
        footer: ["RM3", "RM12", "RA3", "G99"],
        feedCut: 400, feedTravel: 5000, sMax: 1000
      }
    ].map(t => ({ name: t.name, data: t, builtin: true }));
  },

  async loadUserTemplates() {
    this._templates = [];
    try {
      const db = await this._openDB();
      const entries = await new Promise(resolve => {
        const tx = db.transaction('templates', 'readonly');
        const store = tx.objectStore('templates');
        const req = store.getAll();
        req.onsuccess = () => resolve(req.result || []);
        req.onerror = () => resolve([]);
      });
      for (const entry of entries) {
        if (entry && entry.name && entry.data) {
          this._templates.push({ name: entry.name, data: entry.data });
        }
      }
    } catch (_) {}
  },

  list() {
    const all = [...this._builtinTemplates, ...this._templates];
    return [...new Set(all.map(t => t.name))];
  },

  getTemplate(name) {
    return this._templates.find(t => t.name === name) || this._builtinTemplates.find(t => t.name === name);
  },

  getActive() { return this._activeTemplate; },

  setActive(name) {
    this._activeTemplate = name ? this.getTemplate(name) : null;
  },

  async saveTemplate(name, data) {
    data.name = name;
    try {
      const db = await this._openDB();
      await new Promise((resolve, reject) => {
        const tx = db.transaction('templates', 'readwrite');
        tx.objectStore('templates').put({ name, data });
        tx.oncomplete = () => resolve();
        tx.onerror = () => reject(tx.error);
      });
      this._templates.push({ name, data });
      return true;
    } catch (e) {
      console.error('Save template error:', e);
      ui.setStatus('Error saving template: ' + e.message, 'error');
      return false;
    }
  },

  async deleteTemplate(name) {
    if (this._builtinTemplates.some(t => t.name === name)) {
      ui.setStatus('Cannot delete built-in template.', 'error');
      return;
    }
    try {
      const db = await this._openDB();
      await new Promise((resolve, reject) => {
        const tx = db.transaction('templates', 'readwrite');
        tx.objectStore('templates').delete(name);
        tx.oncomplete = () => resolve();
        tx.onerror = () => reject(tx.error);
      });
      this._templates = this._templates.filter(t => t.name !== name);
    } catch (_) {}
  },

  extractFromText(originalText, originalName) {
    const lines = originalText.split('\n');
    const ext = originalName ? (originalName.match(/\.([^.]+)$/) || [])[1] || 'gcode' : 'gcode';
    const lineEnd = originalText.includes('\r\n') ? '\r\n' : originalText.includes('\r') ? '\r' : '\n';

    const knownG = /^(G0|G00|G1|G01|G2|G02|G3|G03|G4|G04|G10|G17|G18|G19|G20|G21|G28|G30|G40|G43|G49|G54|G55|G56|G57|G58|G59|G80|G81|G82|G83|G84|G85|G86|G87|G88|G89|G90|G91|G92|G93|G94|G98|G99)$/i;
    const knownM = /^(M0|M1|M2|M3|M4|M5|M6|M7|M8|M9|M30|M98|M99)$/i;
    const knownLaserOn  = /^(M3|M4|SM3|SM4)$/i;
    const knownLaserOff = /^(M5|RM3|RM4)$/i;

    const customTypes = new Set();
    const toolCodes = new Set();
    let headerLines = [];
    let footerLines = [];
    let firstMoveIdx = -1;
    let lastMoveIdx = -1;
    let laserOnCmd = '';
    let laserOffCmd = '';
    const sValues = [];
    const feedValues = [];

    const parsed = lines.map((raw, i) => {
      const stripped = raw.replace(/\(.*?\)/g, '').replace(/;.*$/, '').trim();
      if (!stripped) return { idx: i, type: '', blank: true };
      const parts = stripped.toUpperCase().split(/\s+/);
      let first = parts[0];
      if (/^N\d+$/.test(first)) first = parts[1] || '';
      const typeParam = first.match(/^([XYZABC])([-\d.]+)$/);
      const type = typeParam ? '' : first;
      return { idx: i, type, blank: false, raw: stripped };
    });

    for (let i = 0; i < parsed.length; i++) {
      const p = parsed[i];
      if (p.blank) continue;
      const t = p.type;
      if (!t) {
        if (firstMoveIdx === -1) firstMoveIdx = i;
        lastMoveIdx = i;
        continue;
      }
      if (knownG.test(t)) {
        if (firstMoveIdx === -1) firstMoveIdx = i;
        lastMoveIdx = i;
      } else if (knownM.test(t)) {
        if (knownLaserOn.test(t))  { if (!laserOnCmd)  laserOnCmd = p.raw; }
        if (knownLaserOff.test(t)) { if (!laserOffCmd) laserOffCmd = p.raw; }
      } else if (knownLaserOn.test(t) || knownLaserOff.test(t)) {
        // Custom laser ON/OFF commands (e.g. SM3 / RM3)
        if (knownLaserOn.test(t))  { if (!laserOnCmd)  laserOnCmd = p.raw; }
        if (knownLaserOff.test(t)) { if (!laserOffCmd) laserOffCmd = p.raw; }
      } else if (t.startsWith('T')) {
        toolCodes.add(t);
      } else {
        customTypes.add(t);
        if (firstMoveIdx === -1) firstMoveIdx = i;
        lastMoveIdx = i;
      }
    }

    if (firstMoveIdx > 0) headerLines = lines.slice(0, firstMoveIdx).map(l => l.trimEnd());
    if (lastMoveIdx >= 0 && lastMoveIdx < lines.length - 1) footerLines = lines.slice(lastMoveIdx + 1).map(l => l.trimEnd());

    for (const c of parsed) {
      if (c.blank || c.type) continue;
      const m = c.raw.match(/\bF([\d.]+)/);
      if (m) feedValues.push(parseFloat(m[1]));
      const sm = c.raw.match(/\bS([\d.]+)/);
      if (sm) sValues.push(parseFloat(sm[1]));
    }

    const beforeMove = {};
    const afterMove = {};
    for (let i = 0; i < parsed.length; i++) {
      const p = parsed[i];
      const isMove = !p.blank && (p.type === 'G1' || p.type === 'G01' || (!p.type && p.raw && /[XYZ]/.test(p.raw)));
      if (!isMove) continue;
      if (i > 0 && !parsed[i - 1].blank) {
        const pf = parsed[i - 1].type || parsed[i - 1].raw?.split(/\s+/)[0] || '';
        const key = pf.toUpperCase();
        if (key) beforeMove[key] = { count: (beforeMove[key]?.count || 0) + 1, full: lines[parsed[i - 1].idx].split(';')[0].trim() };
      }
      if (i + 1 < parsed.length && !parsed[i + 1].blank) {
        const nf = parsed[i + 1].type || parsed[i + 1].raw?.split(/\s+/)[0] || '';
        const key = nf.toUpperCase();
        if (key) afterMove[key] = { count: (afterMove[key]?.count || 0) + 1, full: lines[parsed[i + 1].idx].split(';')[0].trim() };
      }
    }

    if (!laserOnCmd) {
      const best = Object.values(beforeMove).sort((a, b) => b.count - a.count)[0];
      if (best) laserOnCmd = best.full;
    }
    if (!laserOffCmd) {
      const best = Object.values(afterMove).sort((a, b) => b.count - a.count)[0];
      if (best) laserOffCmd = best.full;
    }

    const feedCut = feedValues.length ? Math.round(feedValues.reduce((a, b) => a + b) / feedValues.length) : 3000;
    const feedTravel = 8000;
    const sMax = sValues.length ? Math.max(...sValues) : 1000;

    let author = '';
    let programName = '';
    for (const h of headerLines) {
      const authMatch = h.match(/;\s*Autor\s*:\s*(.+)/i);
      if (authMatch) author = authMatch[1].trim();
      const nameMatch = h.match(/;\s*(?:Programmname|Program\s*Name)\s*:\s*(.+)/i);
      if (nameMatch) programName = nameMatch[1].trim();
    }

    return {
      name: '',
      author,
      programName,
      ext,
      lineEnd,
      customCommands: [...customTypes].sort(),
      toolCodes: [...toolCodes].sort(),
      laserOnCmd,
      laserOffCmd,
      header: headerLines,
      footer: footerLines,
      feedCut,
      feedTravel,
      sMax,
      originalName,
      extractedAt: new Date().toISOString()
    };
  },

  extractFromCommands(commands, originalText, originalName) {
    return this.extractFromText(originalText || '', originalName || '');
  },

  getTemplateOptions(name) {
    const passesOpt = { section: 'Passes', options: [
      { id: 'passes', label: 'Passes', type: 'select', values: [1,2,3,4,5,6,8,10], default: 1, unit: '' },
      { id: 'zStep', label: 'Z Step', type: 'select', values: [0, -0.05, -0.1, -0.2, -0.5, -1], default: 0, unit: 'mm' },
    ]};
    const opts = {
      "SM Motion Control (SM300)": [
        passesOpt,
        { section: 'Laser Program', options: [
          { id: 'laserProgram', label: 'Program (RLAD)', type: 'select', values: [44, 45, 50, 55, 60, 65, 70], default: 55, unit: '' },
          { id: 'rrbmParams', label: 'Buffer (RRBM)', type: 'select', values: ['50;56', '50;60', '50;65', '55;56'], default: '50;56', unit: '' },
        ]},
        { section: 'Feed Rates', options: [
          { id: 'feedCut', label: 'Cut feed', type: 'select', values: [20, 40, 80, 100, 200, 400, 500], default: 400, unit: 'mm/min' },
          { id: 'feedTravel', label: 'Travel feed', type: 'select', values: [2000, 3000, 5000, 8000, 10000], default: 5000, unit: 'mm/min' },
        ]},
        { section: 'Focus', options: [
          { id: 'focusZ', label: 'Focus Z', type: 'select', values: [-200, -208, -215, -220, -222, -228, -230], default: -220, unit: 'mm' },
        ]},
        { section: 'Gas', options: [
          { id: 'gas', label: 'Shield gas', type: 'select', values: ['SM12', 'none'], default: 'SM12' },
        ]},
        { section: 'Safety', options: [
          { id: 'safetyOn', label: 'Header safety', type: 'select', values: ['SA3', 'none'], default: 'SA3' },
          { id: 'safetyOff', label: 'Footer safety', type: 'select', values: ['RA3', 'RA4', 'none'], default: 'RA3' },
          { id: 'laserCheck', label: 'Laser check', type: 'select', values: ['G22$L_TEST$01', 'none'], default: 'G22$L_TEST$01' },
        ]},
      ],
      "GRBL 1.1h": [
        passesOpt,
        { section: 'Laser', options: [
          { id: 'sMax', label: 'Power (S)', type: 'select', values: [100, 250, 500, 750, 1000], default: 1000, unit: '' },
          { id: 'laserMode', label: 'Laser mode', type: 'select', values: ['M4 (dynamic)', 'M3 (constant)'], default: 'M4 (dynamic)' },
        ]},
        { section: 'Feed Rates', options: [
          { id: 'feedCut', label: 'Cut feed', type: 'select', values: [100, 200, 300, 500, 1000, 2000, 3000, 5000], default: 3000, unit: 'mm/min' },
          { id: 'feedTravel', label: 'Travel feed', type: 'select', values: [3000, 5000, 6000, 8000, 10000], default: 6000, unit: 'mm/min' },
        ]},
        { section: 'Homing', options: [
          { id: 'homing', label: 'Home on start', type: 'select', values: ['$H (home)', 'none'], default: '$H (home)' },
        ]},
        { section: 'Safety', options: [
          { id: 'spindleOff', label: 'Spindle off', type: 'select', values: ['M5 S0', 'M5'], default: 'M5 S0' },
          { id: 'returnHome', label: 'Return home', type: 'select', values: ['G0 X0 Y0', 'none'], default: 'G0 X0 Y0' },
        ]},
      ],
      "Smoothieware": [
        passesOpt,
        { section: 'Laser', options: [
          { id: 'sMax', label: 'Power (S)', type: 'select', values: [100, 250, 500, 750, 1000], default: 1000, unit: '' },
          { id: 'laserMode', label: 'Laser mode', type: 'select', values: ['M3 (PWM)', 'M4 (dynamic)'], default: 'M3 (PWM)' },
        ]},
        { section: 'Feed Rates', options: [
          { id: 'feedCut', label: 'Cut feed', type: 'select', values: [100, 200, 300, 500, 1000, 2000, 3000, 5000], default: 3000, unit: 'mm/min' },
          { id: 'feedTravel', label: 'Travel feed', type: 'select', values: [3000, 5000, 6000, 8000, 10000], default: 6000, unit: 'mm/min' },
        ]},
        { section: 'Laser Config', options: [
          { id: 'laserPin', label: 'Laser pin', type: 'select', values: ['P1.7 (PWM)', 'P2.0 (PWM)', 'P2.5 (PWM)'], default: 'P1.7 (PWM)' },
          { id: 'maxPower', label: 'Max power (%)', type: 'select', values: [50, 60, 70, 80, 90, 100], default: 100, unit: '%' },
        ]},
        { section: 'Safety', options: [
          { id: 'spindleOff', label: 'Spindle off', type: 'select', values: ['M5', 'M5 S0'], default: 'M5' },
          { id: 'returnHome', label: 'Return home', type: 'select', values: ['G28', 'G0 X0 Y0', 'none'], default: 'G28' },
        ]},
      ],
      "Marlin (Laser)": [
        passesOpt,
        { section: 'Laser', options: [
          { id: 'sMax', label: 'Power (S)', type: 'select', values: [100, 250, 500, 750, 1000], default: 1000, unit: '' },
          { id: 'laserMode', label: 'Laser mode', type: 'select', values: ['M3 (PWM)', 'M4 (dynamic)'], default: 'M3 (PWM)' },
        ]},
        { section: 'Feed Rates', options: [
          { id: 'feedCut', label: 'Cut feed', type: 'select', values: [100, 200, 300, 500, 1000, 2000, 3000, 5000], default: 3000, unit: 'mm/min' },
          { id: 'feedTravel', label: 'Travel feed', type: 'select', values: [3000, 5000, 6000, 8000, 10000], default: 6000, unit: 'mm/min' },
        ]},
        { section: 'Motion', options: [
          { id: 'accelX', label: 'Accel X', type: 'select', values: [100, 200, 500, 1000, 2000, 3000], default: 500, unit: 'mm/s²' },
          { id: 'accelY', label: 'Accel Y', type: 'select', values: [100, 200, 500, 1000, 2000, 3000], default: 500, unit: 'mm/s²' },
          { id: 'jerkXY', label: 'Jerk XY', type: 'select', values: [5, 8, 10, 15, 20], default: 10, unit: 'mm/s' },
        ]},
        { section: 'Safety', options: [
          { id: 'spindleOff', label: 'Spindle off', type: 'select', values: ['M5', 'M5 S0'], default: 'M5' },
          { id: 'steppersOff', label: 'Steppers off', type: 'select', values: ['M84', 'none'], default: 'M84' },
          { id: 'returnHome', label: 'Return home', type: 'select', values: ['G28', 'G0 X0 Y0', 'none'], default: 'G28' },
        ]},
      ],
    };
    return opts[name] || [];
  },

  applyToSvgConverter(template, userOptions) {
    if (!template) return null;
    const t = template.data || template;
    const opts = userOptions || {};
    // Handle laser mode selection (M3 vs M4)
    let laserOnCmd = t.laserOnCmd || 'M4';
    let laserOffCmd = t.laserOffCmd || 'M5';
    if (opts.laserMode) {
      if (opts.laserMode.includes('M4')) {
        laserOnCmd = laserOnCmd.replace(/^M[34]/, 'M4');
      } else {
        laserOnCmd = laserOnCmd.replace(/^M[34]/, 'M3');
      }
    }
    if (opts.spindleOff) {
      laserOffCmd = opts.spindleOff;
    }
    return {
      laser: {
        feedCut: parseFloat(opts.feedCut) || t.feedCut || 3000,
        feedTravel: parseFloat(opts.feedTravel) || t.feedTravel || 8000,
        sMax: parseFloat(opts.sMax) || t.sMax || 1000,
        laserOnCmd,
        laserOffCmd,
        passes: parseInt(opts.passes) || 1,
        zStep: parseFloat(opts.zStep) || 0,
      },
      header: this._buildHeader(t, opts),
      footer: this._buildFooter(t, opts),
      commandComments: t.commandComments || {},
      options: { laserOnCmd: t.laserOnCmd, laserOffCmd: t.laserOffCmd, ...(opts || {}) },
    };
  },

  _buildHeader(t, opts) {
    if (!t.header) return [];
    const hdr = [...t.header];
    // SM300 options
    if (opts.gas === 'none') {
      const idx = hdr.findIndex(l => l.trim() === 'SM12');
      if (idx >= 0) hdr.splice(idx, 1);
    }
    if (opts.safetyOn === 'none') {
      const idx = hdr.findIndex(l => l.trim() === 'SA3');
      if (idx >= 0) hdr.splice(idx, 1);
    }
    if (opts.laserCheck === 'none') {
      const idx = hdr.findIndex(l => l.trim().startsWith('G22$L_TEST$'));
      if (idx >= 0) hdr.splice(idx, 1);
    }
    // GRBL/Smoothieware/Marlin options
    if (opts.homing === 'none') {
      const idx = hdr.findIndex(l => l.trim() === '$H');
      if (idx >= 0) hdr.splice(idx, 1);
    }
    return hdr;
  },

  _buildFooter(t, opts) {
    if (!t.footer) return [];
    const ftr = [...t.footer];
    // SM300 options
    if (opts.gas === 'none') {
      const idx = ftr.findIndex(l => l.trim() === 'RM12');
      if (idx >= 0) ftr.splice(idx, 1);
    }
    if (opts.safetyOff === 'none') {
      const idx = ftr.findIndex(l => /^RA[34]$/.test(l.trim()));
      if (idx >= 0) ftr.splice(idx, 1);
    } else if (opts.safetyOff && opts.safetyOff !== 'none') {
      const idx = ftr.findIndex(l => /^RA[34]$/.test(l.trim()));
      if (idx >= 0) ftr[idx] = opts.safetyOff;
    }
    // GRBL/Smoothieware/Marlin options
    if (opts.returnHome === 'none') {
      const idx = ftr.findIndex(l => /^(G28|G0 X0 Y0)$/.test(l.trim()));
      if (idx >= 0) ftr.splice(idx, 1);
    } else if (opts.returnHome) {
      const idx = ftr.findIndex(l => /^(G28|G0 X0 Y0)$/.test(l.trim()));
      if (idx >= 0) ftr[idx] = opts.returnHome;
    }
    if (opts.steppersOff === 'none') {
      const idx = ftr.findIndex(l => l.trim() === 'M84');
      if (idx >= 0) ftr.splice(idx, 1);
    }
    return ftr;
  }
};